use super::*;

#[utoipa::path(
    get,
    path = "/health",
    tag = "platform",
    security(),
    responses(
        (status = 200, description = "Service is healthy", body = super::openapi::HealthResponse),
    ),
)]
pub(super) async fn health() -> Json<Value> {
    Json(json!({ "status": "ok" }))
}

#[utoipa::path(
    get,
    path = "/readyz",
    tag = "platform",
    security(),
    responses(
        (status = 200, description = "Operational and metric stores ready", body = super::openapi::HealthResponse),
        (status = 503, description = "Not ready", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn readyz(State(state): State<Arc<AppState>>) -> AppResult<Json<Value>> {
    if state.config.service_plane.includes_data() && !store::ready(&state.store).await {
        return Err(AppError::service_unavailable(
            "clickhouse operational store is not ready",
        ));
    }
    if !state.config.service_plane.includes_data() && !store::control_ready(&state.store).await {
        return Err(AppError::service_unavailable(
            "clickhouse control store is not ready",
        ));
    }
    Ok(Json(json!({ "status": "ok" })))
}

pub(super) async fn metrics() -> Response {
    (
        [(header::CONTENT_TYPE, "text/plain; version=0.0.4")],
        "instantml_rust_build_info{service=\"rust-server\"} 1\n",
    )
        .into_response()
}

/// Serve the OpenAPI spec generated by utoipa from `#[utoipa::path]`
/// annotations on each handler. The response is filtered to only include
/// paths the active service plane actually serves.
pub(super) async fn openapi_json(State(state): State<Arc<AppState>>) -> Json<Value> {
    use utoipa::OpenApi as _;
    let utoipa_spec = super::openapi::ApiDoc::openapi();
    let service_plane = state.config.service_plane;
    let mut spec =
        serde_json::to_value(&utoipa_spec).expect("utoipa OpenApi is always JSON-serializable");
    if let Some(spec_obj) = spec.as_object_mut() {
        if let Some(Value::Object(paths)) = spec_obj.get_mut("paths") {
            paths.retain(|path, _| openapi_path_available_for_plane(path, service_plane));
        }
        spec_obj.insert(
            "x-instantml-service-plane".to_string(),
            json!(service_plane.as_str()),
        );
    }
    Json(spec)
}

fn openapi_path_available_for_plane(
    path: &str,
    service_plane: crate::config::ServicePlaneRole,
) -> bool {
    if matches!(
        path,
        "/health" | "/healthz" | "/readyz" | "/metrics" | "/openapi.json" | "/api/auth/config"
    ) {
        return true;
    }
    if path.starts_with("/api/auth/")
        || path == "/api/users"
        || path == "/api/orgs"
        || path == "/api/orgs/memberships"
        || path == "/api/orgs/name-availability"
        || path == "/api/dashboard/preferences"
        || path == "/api/workspace-views"
        || path.starts_with("/api/workspace-views/")
        || path.starts_with("/api/orgs/{org_id}/")
    {
        return service_plane.includes_control();
    }
    service_plane.includes_data()
}

#[utoipa::path(
    get,
    path = "/api/auth/config",
    tag = "auth",
    security(),
    responses(
        (status = 200, description = "Frontend auth provider availability", body = super::openapi::AuthConfigResponse),
    ),
)]
pub(super) async fn auth_config(State(state): State<Arc<AppState>>) -> Json<Value> {
    let exposes_auth_routes = state.config.service_plane.includes_control();
    Json(json!({
        "dev_auth_enabled": exposes_auth_routes && state.config.dev_auth_enabled,
        "managed_clerk_enabled": exposes_auth_routes && state.config.managed_clerk_enabled,
        "service_plane": state.config.service_plane.as_str()
    }))
}

#[utoipa::path(
    post,
    path = "/api/auth/dev/google",
    tag = "auth",
    request_body = crate::domain::DevGoogleAuthRequest,
    security(),
    responses(
        (status = 200, description = "Session payload; HttpOnly session cookie is set on the response", body = crate::domain::AuthSessionPayload),
        (status = 401, description = "Dev auth is not enabled", body = super::openapi::ErrorResponse),
        (status = 403, description = "Origin not allowed", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn auth_dev_google(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Response> {
    if !state.config.dev_auth_enabled {
        return Err(AppError::unauthorized(
            "local development auth is not enabled",
        ));
    }
    validate_mutation_origin(&state, &headers)?;
    let input = read_json::<DevGoogleAuthRequest>(&headers, bytes, state.config.max_body_bytes)?;
    let created = store::create_dev_google_session(&state.store, input).await?;
    json_with_session_cookie(&state, &headers, created.payload, &created.token)
}

#[utoipa::path(
    post,
    path = "/api/auth/clerk",
    tag = "auth",
    request_body = crate::domain::ClerkAuthRequest,
    security(),
    responses(
        (status = 200, description = "Session payload (with optional onboarding API key); HttpOnly session cookie is set", body = super::openapi::AuthSessionWithOnboardingKey),
        (status = 401, description = "Clerk auth not configured or token invalid", body = super::openapi::ErrorResponse),
        (status = 403, description = "Origin not allowed or signup restricted", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn auth_clerk(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Response> {
    if !state.config.managed_clerk_enabled {
        return Err(AppError::unauthorized(
            "managed Clerk auth is not configured",
        ));
    }
    validate_mutation_origin_required(&state, &headers)?;
    let input = read_json::<ClerkAuthRequest>(&headers, bytes, state.config.max_body_bytes)?;
    let token = input
        .token
        .clone()
        .ok_or_else(|| AppError::validation("token is required"))?;
    let secret_key = state
        .config
        .clerk_secret_key
        .as_deref()
        .ok_or_else(|| AppError::unauthorized("managed Clerk auth is not configured"))?;
    let principal = crate::managed_auth::verify_clerk_session_token(
        secret_key,
        &state.config.clerk_api_base,
        state.config.clerk_jwt_issuer.as_deref(),
        &token,
        state.config.clerk_session_max_token_age,
    )
    .await?;
    validate_clerk_signup_allowed(&state.config, &principal.email, &input)?;
    let created = store::create_clerk_session(&state.store, principal, input).await?;
    let mut response_body = serde_json::to_value(&created.payload)
        .map_err(|_| AppError::internal("failed to serialize auth payload"))?;
    if let Some(onboarding_key) = &created.onboarding_api_key {
        if let Some(obj) = response_body.as_object_mut() {
            obj.insert(
                "onboarding_api_key".to_string(),
                serde_json::to_value(onboarding_key)
                    .map_err(|_| AppError::internal("failed to serialize onboarding key"))?,
            );
        }
    }
    json_with_session_cookie(&state, &headers, response_body, &created.token)
}

#[utoipa::path(
    get,
    path = "/api/auth/session",
    tag = "auth",
    security(("browserSession" = [])),
    responses(
        (status = 200, description = "Authenticated session payload", body = crate::domain::AuthSessionPayload),
        (status = 200, description = "Unauthenticated session", body = super::openapi::AuthSessionUnauthenticated),
    ),
)]
pub(super) async fn auth_session(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> AppResult<Response> {
    let Some(token) = session_cookie(&headers) else {
        return Ok(Json(json!({ "authenticated": false })).into_response());
    };
    match store::authenticate_session(&state.store, token).await {
        Ok(payload) => Ok(Json(payload).into_response()),
        Err(_) => {
            let mut response = Json(json!({ "authenticated": false })).into_response();
            response
                .headers_mut()
                .append(header::SET_COOKIE, header_value(&clear_session_cookie())?);
            Ok(response)
        }
    }
}

#[utoipa::path(
    post,
    path = "/api/auth/logout",
    tag = "auth",
    security(("browserSession" = [])),
    responses(
        (status = 200, description = "Session revoked and cookie cleared", body = super::openapi::AuthSessionUnauthenticated),
    ),
)]
pub(super) async fn auth_logout(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> AppResult<Response> {
    validate_mutation_origin(&state, &headers)?;
    if let Some(token) = session_cookie(&headers) {
        store::revoke_session(&state.store, token).await?;
    }
    let mut response = Json(json!({ "authenticated": false })).into_response();
    response
        .headers_mut()
        .append(header::SET_COOKIE, header_value(&clear_session_cookie())?);
    Ok(response)
}

/// Re-point the caller's session at a different org they belong to.
///
/// Used by the dashboard org-switcher. The session token is unchanged — only
/// the bound `org_id` on the session row is updated, so subsequent requests
/// from the same cookie scope to the newly selected org.
#[utoipa::path(
    post,
    path = "/api/auth/switch-organization",
    tag = "auth",
    request_body = crate::domain::SwitchOrganizationRequest,
    security(("browserSession" = [])),
    responses(
        (status = 200, description = "Refreshed session payload bound to the target org", body = crate::domain::AuthSessionPayload),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Missing session", body = super::openapi::ErrorResponse),
        (status = 403, description = "No active membership in target organization", body = super::openapi::ErrorResponse),
        (status = 404, description = "Organization not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn auth_switch_organization(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Response> {
    validate_mutation_origin(&state, &headers)?;
    let token = session_cookie(&headers)
        .ok_or_else(|| AppError::unauthorized("missing session"))?
        .to_string();
    let input =
        read_json::<SwitchOrganizationRequest>(&headers, bytes, state.config.max_body_bytes)?;
    let target_org_id = input
        .org_id
        .ok_or_else(|| AppError::validation("org_id is required"))?;
    let payload = store::switch_session_organization(&state.store, &token, target_org_id).await?;
    Ok(Json(payload).into_response())
}

/// List the orgs the calling session-authenticated user belongs to.
///
/// Returns membership-decorated org summaries (role, member count, slug)
/// for the org-switcher dropdown. Distinct from `/api/orgs` which is a
/// bootstrap-only admin route.
#[utoipa::path(
    get,
    path = "/api/orgs/memberships",
    tag = "orgs",
    security(("browserSession" = [])),
    responses(
        (status = 200, description = "Membership summaries decorated with role, member count, slug", body = super::openapi::OrgMembershipsEnvelope),
        (status = 401, description = "Missing session", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_org_memberships(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> AppResult<Json<Value>> {
    let session = session_context(&state, &headers).await?;
    let memberships =
        store::list_user_org_memberships(&state.store, session.user.id, session.organization.id)
            .await?;
    Ok(Json(json!({ "memberships": memberships })))
}

// --- Device-code (RFC 8628) handlers ---

#[utoipa::path(
    post,
    path = "/api/auth/device-code/start",
    tag = "auth",
    request_body = crate::domain::DeviceCodeStartRequest,
    security(),
    responses(
        (status = 200, description = "Device-code grant initiated", body = super::openapi::DeviceCodeStartResponse),
    ),
)]
pub(super) async fn device_code_start(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let input = read_json::<DeviceCodeStartRequest>(&headers, bytes, state.config.max_body_bytes)?;
    let client_info = input
        .client_info
        .map(|info| json!({ "name": info.name, "version": info.version }));
    let frontend_base_url = state
        .config
        .frontend_base_url
        .as_deref()
        .or_else(|| {
            state
                .config
                .allowed_frontend_origins
                .first()
                .map(String::as_str)
        })
        .unwrap_or("http://localhost:3000");
    let result = store::device_code_start(&state.store, frontend_base_url, client_info).await?;
    Ok(Json(result))
}

#[utoipa::path(
    post,
    path = "/api/auth/device-code/poll",
    tag = "auth",
    request_body = crate::domain::DeviceCodePollRequest,
    security(),
    responses(
        (status = 200, description = "status: pending | authorized | denied | expired", body = super::openapi::DeviceCodePollResponse),
        (status = 429, description = "slow_down: polling too fast", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn device_code_poll(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let input = read_json::<DeviceCodePollRequest>(&headers, bytes, state.config.max_body_bytes)?;
    let raw_device_code = input
        .device_code
        .ok_or_else(|| AppError::validation("device_code is required"))?;
    let result = store::device_code_poll(&state.store, &raw_device_code).await?;
    Ok(Json(result))
}

#[utoipa::path(
    post,
    path = "/api/auth/device-code/confirm",
    tag = "auth",
    request_body = crate::domain::DeviceCodeConfirmRequest,
    security(("browserSession" = [])),
    responses(
        (status = 200, description = "Grant confirmed", body = super::openapi::DeviceCodeConfirmResponse),
        (status = 401, description = "Missing session", body = super::openapi::ErrorResponse),
        (status = 404, description = "user_code not found or expired", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn device_code_confirm(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let input =
        read_json::<DeviceCodeConfirmRequest>(&headers, bytes, state.config.max_body_bytes)?;
    let raw_user_code = input
        .user_code
        .ok_or_else(|| AppError::validation("user_code is required"))?;
    // Requires a valid browser session.
    let session_payload = session_context(&state, &headers).await?;
    let result = store::device_code_confirm(
        &state.store,
        session_payload.user.id,
        session_payload.organization.id,
        &raw_user_code,
    )
    .await?;
    Ok(Json(result))
}

// --- End device-code handlers ---

#[utoipa::path(
    get,
    path = "/api/dashboard/preferences",
    tag = "dashboard",
    security(("browserSession" = []), ("bearerApiKey" = [])),
    responses(
        (status = 200, description = "Dashboard preferences for the caller's tenant", body = super::openapi::DashboardPreferencesEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn get_dashboard_preferences(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, false).await?;
    Ok(Json(
        store::get_dashboard_preferences(&state.store, &ctx).await?,
    ))
}

#[utoipa::path(
    put,
    path = "/api/dashboard/preferences",
    tag = "dashboard",
    request_body = crate::domain::UpdateDashboardPreferencesRequest,
    security(("browserSession" = []), ("bearerApiKey" = [])),
    responses(
        (status = 200, description = "Updated dashboard preferences", body = super::openapi::DashboardPreferencesEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn update_dashboard_preferences(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, false).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    let input = read_json::<UpdateDashboardPreferencesRequest>(
        &headers,
        bytes,
        state.config.max_body_bytes,
    )?;
    Ok(Json(
        store::update_dashboard_preferences(&state.store, &ctx, input).await?,
    ))
}

#[utoipa::path(
    get,
    path = "/api/workspace-views",
    tag = "dashboard",
    params(
        ("limit" = Option<i64>, Query, description = "Page size"),
        ("cursor" = Option<String>, Query, description = "Pagination cursor"),
    ),
    security(("browserSession" = []), ("bearerApiKey" = [])),
    responses(
        (status = 200, description = "Saved workspace view summaries", body = super::openapi::WorkspaceViewSummariesEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_workspace_views(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, false).await?;
    Ok(Json(
        store::list_workspace_views(&state.store, &ctx, &query).await?,
    ))
}

#[utoipa::path(
    post,
    path = "/api/workspace-views",
    tag = "dashboard",
    request_body = crate::domain::SaveWorkspaceViewRequest,
    security(("browserSession" = []), ("bearerApiKey" = [])),
    responses(
        (status = 200, description = "Created workspace view", body = super::openapi::WorkspaceViewEnvelope),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn create_workspace_view(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, false).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    let input =
        read_json::<SaveWorkspaceViewRequest>(&headers, bytes, state.config.max_body_bytes)?;
    Ok(Json(
        store::create_workspace_view(&state.store, &ctx, input).await?,
    ))
}

#[utoipa::path(
    get,
    path = "/api/workspace-views/{view_id}",
    tag = "dashboard",
    params(
        ("view_id" = String, Path, description = "Workspace view UUID"),
    ),
    security(("browserSession" = []), ("bearerApiKey" = [])),
    responses(
        (status = 200, description = "Workspace view", body = super::openapi::WorkspaceViewEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Workspace view not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn get_workspace_view(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(view_id): Path<String>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, false).await?;
    let view_id = parse_uuid(&view_id, "workspace view not found")?;
    Ok(Json(
        store::get_workspace_view(&state.store, &ctx, view_id).await?,
    ))
}

#[utoipa::path(
    put,
    path = "/api/workspace-views/{view_id}",
    tag = "dashboard",
    params(
        ("view_id" = String, Path, description = "Workspace view UUID"),
    ),
    request_body = crate::domain::SaveWorkspaceViewRequest,
    security(("browserSession" = []), ("bearerApiKey" = [])),
    responses(
        (status = 200, description = "Updated workspace view", body = super::openapi::WorkspaceViewEnvelope),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Workspace view not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn update_workspace_view(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(view_id): Path<String>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, false).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    let view_id = parse_uuid(&view_id, "workspace view not found")?;
    let input =
        read_json::<SaveWorkspaceViewRequest>(&headers, bytes, state.config.max_body_bytes)?;
    Ok(Json(
        store::update_workspace_view(&state.store, &ctx, view_id, input).await?,
    ))
}

#[utoipa::path(
    post,
    path = "/api/users",
    tag = "orgs",
    request_body = crate::domain::CreateUserRequest,
    security(("bootstrapToken" = [])),
    responses(
        (status = 200, description = "Created user row", body = super::openapi::UserEnvelope),
        (status = 401, description = "Bootstrap token required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn create_user(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    require_bootstrap(&state, &headers)?;
    let input = read_json::<CreateUserRequest>(&headers, bytes, state.config.max_body_bytes)?;
    Ok(Json(
        json!({ "user": store::create_user(&state.store, input).await? }),
    ))
}

#[utoipa::path(
    get,
    path = "/api/users",
    tag = "orgs",
    security(("bootstrapToken" = [])),
    responses(
        (status = 200, description = "Bootstrap-visible user rows", body = super::openapi::UsersEnvelope),
        (status = 401, description = "Bootstrap token required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_users(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> AppResult<Json<Value>> {
    require_bootstrap(&state, &headers)?;
    Ok(Json(
        json!({ "users": store::list_users(&state.store).await? }),
    ))
}

#[utoipa::path(
    post,
    path = "/api/orgs",
    tag = "orgs",
    request_body = crate::domain::CreateOrganizationRequest,
    security(("bootstrapToken" = [])),
    responses(
        (status = 200, description = "Bootstrapped organization row", body = super::openapi::OrganizationEnvelope),
        (status = 401, description = "Bootstrap token required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn create_org(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    require_bootstrap(&state, &headers)?;
    let input =
        read_json::<CreateOrganizationRequest>(&headers, bytes, state.config.max_body_bytes)?;
    Ok(Json(
        json!({ "organization": store::create_organization(&state.store, input).await? }),
    ))
}

#[utoipa::path(
    get,
    path = "/api/orgs",
    tag = "orgs",
    security(("browserSession" = []), ("bootstrapToken" = [])),
    responses(
        (status = 200, description = "List of organizations visible to the caller", body = super::openapi::OrganizationsEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_orgs(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> AppResult<Json<Value>> {
    require_bootstrap(&state, &headers)?;
    Ok(Json(
        json!({ "organizations": store::list_organizations(&state.store).await? }),
    ))
}

#[utoipa::path(
    get,
    path = "/api/orgs/name-availability",
    tag = "orgs",
    params(
        ("name" = Option<String>, Query, description = "Proposed organization name / slug"),
    ),
    security(),
    responses(
        (status = 200, description = "Availability payload", body = super::openapi::OrganizationNameAvailability),
    ),
)]
pub(super) async fn org_name_availability(
    State(state): State<Arc<AppState>>,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    Ok(Json(
        store::organization_name_availability(&state.store, query.get("name").map(String::as_str))
            .await?,
    ))
}

#[utoipa::path(
    post,
    path = "/api/orgs/{org_id}/api-keys",
    tag = "orgs",
    params(
        ("org_id" = String, Path, description = "Organization UUID"),
    ),
    request_body = crate::domain::CreateApiKeyRequest,
    security(("browserSession" = []), ("bearerApiKey" = []), ("bootstrapToken" = [])),
    responses(
        (status = 200, description = "Created API key plus copy-once plaintext", body = super::openapi::ApiKeyCreatedEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Insufficient role", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn create_api_key(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(org_id): Path<String>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let org_id = parse_uuid(&org_id, "organization not found")?;
    let input = read_json::<CreateApiKeyRequest>(&headers, bytes, state.config.max_body_bytes)?;
    match admin_actor(&state, &headers, org_id).await? {
        Some(user_id) => Ok(Json(
            store::create_api_key_for_user(&state.store, user_id, org_id, input).await?,
        )),
        None => Ok(Json(
            store::create_api_key(&state.store, org_id, input).await?,
        )),
    }
}

#[utoipa::path(
    get,
    path = "/api/orgs/{org_id}/api-keys",
    tag = "orgs",
    params(
        ("org_id" = String, Path, description = "Organization UUID"),
    ),
    security(("browserSession" = []), ("bootstrapToken" = [])),
    responses(
        (status = 200, description = "API keys for the organization", body = super::openapi::ApiKeysEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Insufficient role", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_api_keys(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(org_id): Path<String>,
) -> AppResult<Json<Value>> {
    let org_id = parse_uuid(&org_id, "organization not found")?;
    require_admin_or_bootstrap(&state, &headers, org_id).await?;
    Ok(Json(
        json!({ "api_keys": store::list_api_keys(&state.store, org_id).await? }),
    ))
}

#[utoipa::path(
    post,
    path = "/api/orgs/{org_id}/api-keys/{api_key_id}/revoke",
    tag = "orgs",
    params(
        ("org_id" = String, Path, description = "Organization UUID"),
        ("api_key_id" = String, Path, description = "API key UUID"),
    ),
    security(("browserSession" = []), ("bearerApiKey" = []), ("bootstrapToken" = [])),
    responses(
        (status = 200, description = "Revoked API key row", body = super::openapi::ApiKeyEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Insufficient role", body = super::openapi::ErrorResponse),
        (status = 404, description = "API key not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn revoke_api_key(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path((org_id, api_key_id)): Path<(String, String)>,
) -> AppResult<Json<Value>> {
    let org_id = parse_uuid(&org_id, "organization not found")?;
    if session_cookie(&headers).is_some() {
        validate_mutation_origin(&state, &headers)?;
        reject_demo_session_mutation(&state, &headers).await?;
    }
    require_admin_or_bootstrap(&state, &headers, org_id).await?;
    let api_key_id = parse_uuid(&api_key_id, "api key not found")?;
    Ok(Json(
        json!({ "key": store::revoke_api_key(&state.store, org_id, api_key_id).await? }),
    ))
}

#[utoipa::path(
    post,
    path = "/api/orgs/{org_id}/service-accounts/{service_account_id}/disable",
    tag = "orgs",
    params(
        ("org_id" = String, Path, description = "Organization UUID"),
        ("service_account_id" = String, Path, description = "Service account UUID"),
    ),
    security(("browserSession" = []), ("bearerApiKey" = []), ("bootstrapToken" = [])),
    responses(
        (status = 200, description = "Disabled service account row", body = super::openapi::ServiceAccountEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Insufficient role", body = super::openapi::ErrorResponse),
        (status = 404, description = "Service account not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn disable_service_account(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path((org_id, service_account_id)): Path<(String, String)>,
) -> AppResult<Json<Value>> {
    let org_id = parse_uuid(&org_id, "organization not found")?;
    if session_cookie(&headers).is_some() {
        validate_mutation_origin(&state, &headers)?;
        reject_demo_session_mutation(&state, &headers).await?;
    }
    require_admin_or_bootstrap(&state, &headers, org_id).await?;
    let service_account_id = parse_uuid(&service_account_id, "service account not found")?;
    Ok(Json(json!({
        "service_account": store::disable_service_account(&state.store, org_id, service_account_id).await?
    })))
}

#[utoipa::path(
    post,
    path = "/api/orgs/{org_id}/seats",
    tag = "orgs",
    params(
        ("org_id" = String, Path, description = "Organization UUID"),
    ),
    request_body = crate::domain::ReserveSeatRequest,
    security(("browserSession" = []), ("bootstrapToken" = [])),
    responses(
        (status = 200, description = "Reserved (invited) seat row", body = super::openapi::SeatEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Insufficient role", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn reserve_seat(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(org_id): Path<String>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let org_id = parse_uuid(&org_id, "organization not found")?;
    let input = read_json::<ReserveSeatRequest>(&headers, bytes, state.config.max_body_bytes)?;
    let actor = admin_actor(&state, &headers, org_id).await?;
    Ok(Json(json!({
        "seat": store::reserve_seat(&state.store, actor, org_id, input).await?
    })))
}

#[utoipa::path(
    get,
    path = "/api/orgs/{org_id}/seats",
    tag = "orgs",
    params(
        ("org_id" = String, Path, description = "Organization UUID"),
    ),
    security(("browserSession" = []), ("bootstrapToken" = [])),
    responses(
        (status = 200, description = "Seats for the organization", body = super::openapi::SeatsEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Insufficient role", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_seats(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(org_id): Path<String>,
) -> AppResult<Json<Value>> {
    let org_id = parse_uuid(&org_id, "organization not found")?;
    require_admin_or_bootstrap(&state, &headers, org_id).await?;
    Ok(Json(json!({
        "seats": store::list_seats(&state.store, org_id).await?
    })))
}

#[utoipa::path(
    post,
    path = "/projects",
    tag = "runs",
    request_body = crate::domain::CreateProjectRequest,
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Created or fetched project", body = super::openapi::ProjectEnvelope),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn create_project(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    require_scope(&ctx, "sdk:ingest", &state)?;
    let input = read_json::<CreateProjectRequest>(&headers, bytes, state.config.max_body_bytes)?;
    Ok(Json(
        json!({ "project": store::create_project(&state.store, &ctx, input).await? }),
    ))
}

#[utoipa::path(
    get,
    path = "/projects",
    tag = "runs",
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Projects for the caller's organization", body = super::openapi::ProjectsEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_projects(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    Ok(Json(
        json!({ "projects": store::list_projects(&state.store, &ctx).await? }),
    ))
}

#[utoipa::path(
    post,
    path = "/runs",
    tag = "runs",
    request_body = crate::domain::CreateRunRequest,
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Created run", body = super::openapi::RunEnvelope),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn create_run(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    require_scope(&ctx, "sdk:ingest", &state)?;
    let input = read_json::<CreateRunRequest>(&headers, bytes, state.config.max_body_bytes)?;
    Ok(Json(
        json!({ "run": store::create_run(&state.store, &ctx, input).await? }),
    ))
}

#[utoipa::path(
    get,
    path = "/runs",
    tag = "runs",
    params(
        ("project" = Option<String>, Query, description = "Filter by project name"),
        ("status" = Option<String>, Query, description = "Filter by run status"),
        ("limit" = Option<i64>, Query, description = "Page size (1..=1000)"),
        ("offset" = Option<i64>, Query, description = "Offset for pagination"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Page of runs", body = super::openapi::RunsEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_runs(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    Ok(Json(store::list_runs(&state.store, &ctx, &query).await?))
}

#[utoipa::path(
    get,
    path = "/runs/{run_id}",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Run detail", body = super::openapi::RunEnvelope),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn get_run(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    Ok(Json(
        json!({ "run": store::get_run(&state.store, &ctx, run_id).await? }),
    ))
}

#[utoipa::path(
    patch,
    path = "/runs/{run_id}",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
    ),
    request_body = crate::domain::UpdateRunRequest,
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Updated run", body = super::openapi::RunEnvelope),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn update_run(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    require_scope(&ctx, "sdk:ingest", &state)?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    let input = read_json::<UpdateRunRequest>(&headers, bytes, state.config.max_body_bytes)?;
    Ok(Json(
        json!({ "run": store::update_run(&state.store, &ctx, run_id, input).await? }),
    ))
}

#[utoipa::path(
    post,
    path = "/runs/{run_id}/metrics",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
    ),
    request_body = crate::domain::LogMetricsRequest,
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Inserted point count", body = super::openapi::InsertedEnvelope),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn log_metrics(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    require_scope(&ctx, "sdk:ingest", &state)?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    let (input, raw) =
        read_json_with_raw::<LogMetricsRequest>(&headers, bytes, state.config.max_body_bytes)?;
    let idempotency_key = header_text(&headers, "idempotency-key").map(str::to_string);
    let inserted =
        store::log_metrics(&state.store, &ctx, run_id, raw, input, idempotency_key).await?;
    Ok(Json(json!({ "inserted": inserted })))
}

#[utoipa::path(
    get,
    path = "/runs/{run_id}/metrics",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
        ("key" = Option<String>, Query, description = "Filter by metric key"),
        ("start_step" = Option<f64>, Query, description = "Inclusive start step"),
        ("end_step" = Option<f64>, Query, description = "Inclusive end step"),
        ("limit" = Option<i64>, Query, description = "Page size"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Bounded scalar metric points", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn get_metrics(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    Ok(Json(
        store::get_metrics(&state.store, &ctx, run_id, &query).await?,
    ))
}

#[utoipa::path(
    post,
    path = "/api/runs/{run_id}/logs",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
    ),
    request_body = crate::domain::CreateConsoleLogsRequest,
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Number of inserted console log lines", body = super::openapi::InsertedEnvelope),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn log_console_logs(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    require_scope(&ctx, "sdk:ingest", &state)?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    let (input, raw) = read_json_with_raw::<CreateConsoleLogsRequest>(
        &headers,
        bytes,
        state.config.max_body_bytes,
    )?;
    let idempotency_key = header_text(&headers, "idempotency-key").map(str::to_string);
    let inserted =
        store::log_console_logs(&state.store, &ctx, run_id, raw, input, idempotency_key).await?;
    Ok(Json(json!({ "inserted": inserted })))
}

#[utoipa::path(
    get,
    path = "/api/runs/{run_id}/logs",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
        ("stream" = Option<String>, Query, description = "stdout or stderr"),
        ("limit" = Option<i64>, Query, description = "Page size"),
        ("cursor" = Option<String>, Query, description = "Pagination cursor"),
        ("q" = Option<String>, Query, description = "Substring filter"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Console log page", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_console_logs(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    Ok(Json(
        store::list_console_logs(&state.store, &ctx, run_id, &query).await?,
    ))
}

#[derive(Debug, serde::Deserialize, utoipa::ToSchema)]
pub(super) struct MetricsSeriesRequest {
    pub key: String,
    pub run_ids: Vec<String>,
    #[serde(default)]
    pub limit: Option<i64>,
    #[serde(default)]
    pub start_step: Option<f64>,
    #[serde(default)]
    pub end_step: Option<f64>,
}

#[utoipa::path(
    post,
    path = "/api/metrics/series",
    tag = "runs",
    request_body = MetricsSeriesRequest,
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Per-run metric series keyed by run_id", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn metrics_series(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Json(body): Json<MetricsSeriesRequest>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    let mut query = HashMap::new();
    query.insert("key".to_string(), body.key);
    query.insert("run_ids".to_string(), body.run_ids.join(","));
    if let Some(limit) = body.limit {
        query.insert("limit".to_string(), limit.to_string());
    }
    if let Some(start) = body.start_step {
        query.insert("start_step".to_string(), start.to_string());
    }
    if let Some(end) = body.end_step {
        query.insert("end_step".to_string(), end.to_string());
    }
    Ok(Json(
        store::metrics_series_batched(&state.store, &ctx, &query).await?,
    ))
}

#[utoipa::path(
    get,
    path = "/api/overview",
    tag = "runs",
    params(
        ("project" = Option<String>, Query, description = "Filter by project name"),
        ("status" = Option<String>, Query, description = "Filter by run status"),
        ("q" = Option<String>, Query, description = "Substring search"),
        ("metric_key" = Option<String>, Query, description = "Metric key for best-value column"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Dashboard overview payload", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn overview(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    Ok(Json(store::overview(&state.store, &ctx, &query).await?))
}

#[utoipa::path(
    get,
    path = "/api/runs/summary",
    tag = "runs",
    params(
        ("project" = Option<String>, Query, description = "Filter by project name"),
        ("status" = Option<String>, Query, description = "Filter by run status"),
        ("q" = Option<String>, Query, description = "Substring search"),
        ("sort_by" = Option<String>, Query, description = "Sort key"),
        ("metric_key" = Option<String>, Query, description = "Metric key for ranked column"),
        ("limit" = Option<i64>, Query, description = "Page size"),
        ("offset" = Option<i64>, Query, description = "Offset for pagination"),
        ("cursor" = Option<String>, Query, description = "Pagination cursor"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Run summary page with metric key catalog", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn runs_summary(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    Ok(Json(store::runs_summary(&state.store, &ctx, &query).await?))
}

#[utoipa::path(
    get,
    path = "/api/runs/side-by-side",
    tag = "runs",
    params(
        ("run_ids" = Option<String>, Query, description = "Comma-separated run UUIDs"),
        ("runs" = Option<String>, Query, description = "Alias for run_ids"),
        ("reference_run_id" = Option<String>, Query, description = "Pin a reference run"),
        ("diff_only" = Option<bool>, Query, description = "Only return rows that differ"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Side-by-side comparison rows", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn side_by_side(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    Ok(Json(store::side_by_side(&state.store, &ctx, &query).await?))
}

#[utoipa::path(
    post,
    path = "/api/runs/{run_id}/attributes",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
    ),
    request_body = crate::domain::CreateAttributesRequest,
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Created attribute rows", body = super::openapi::AttributesEnvelope),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn create_attributes(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    require_scope(&ctx, "sdk:ingest", &state)?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    let input = read_json::<CreateAttributesRequest>(&headers, bytes, state.config.max_body_bytes)?;
    Ok(Json(
        json!({ "attributes": store::create_attributes(&state.store, &ctx, run_id, input).await? }),
    ))
}

#[utoipa::path(
    get,
    path = "/api/runs/{run_id}/attributes",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
        ("type" = Option<String>, Query, description = "Filter by attribute kind"),
        ("path_prefix" = Option<String>, Query, description = "Filter by path prefix"),
        ("limit" = Option<i64>, Query, description = "Page size"),
        ("offset" = Option<i64>, Query, description = "Offset for pagination"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Typed attribute rows for the run", body = super::openapi::AttributesEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_attributes(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    Ok(Json(
        json!({ "attributes": store::list_attributes(&state.store, &ctx, run_id, &query).await? }),
    ))
}

#[utoipa::path(
    post,
    path = "/api/runs/{run_id}/objects",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
    ),
    request_body = crate::domain::CreateObjectRequest,
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Created rich object", body = super::openapi::ObjectEnvelope),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn create_object(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    require_scope(&ctx, "sdk:ingest", &state)?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    let input = read_json::<CreateObjectRequest>(&headers, bytes, state.config.max_body_bytes)?;
    Ok(Json(json!({
        "object": store::create_object(&state.store, &ctx, run_id, input).await?
    })))
}

#[utoipa::path(
    get,
    path = "/api/runs/{run_id}/objects",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
        ("kind" = Option<String>, Query, description = "Filter by object kind"),
        ("key" = Option<String>, Query, description = "Filter by object key"),
        ("limit" = Option<i64>, Query, description = "Page size"),
        ("offset" = Option<i64>, Query, description = "Offset for pagination"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Rich object page", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_objects(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    Ok(Json(
        store::list_objects(&state.store, &ctx, run_id, &query).await?,
    ))
}

#[utoipa::path(
    get,
    path = "/api/objects/{object_id}/rows",
    tag = "runs",
    params(
        ("object_id" = i64, Path, description = "Object integer id"),
        ("limit" = Option<i64>, Query, description = "Page size"),
        ("offset" = Option<i64>, Query, description = "Offset for pagination"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Table object rows", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Object not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_object_rows(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(object_id): Path<String>,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    let object_id = object_id
        .parse::<i64>()
        .map_err(|_| AppError::not_found("object not found"))?;
    Ok(Json(
        store::list_object_rows(&state.store, &ctx, object_id, &query).await?,
    ))
}

#[utoipa::path(
    post,
    path = "/api/runs/{run_id}/artifacts",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
    ),
    request_body = crate::domain::CreateArtifactRequest,
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Created artifact metadata", body = super::openapi::ArtifactEnvelope),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn create_artifact(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    require_scope(&ctx, "artifacts:write", &state)?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    let input = read_json::<CreateArtifactRequest>(&headers, bytes, state.config.max_body_bytes)?;
    Ok(Json(
        json!({ "artifact": store::create_artifact(&state.store, &ctx, run_id, input).await? }),
    ))
}

#[utoipa::path(
    post,
    path = "/api/runs/{run_id}/artifacts/upload",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
    ),
    request_body = crate::domain::UploadArtifactRequest,
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Created artifact with stored bytes", body = super::openapi::ArtifactEnvelope),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Artifact byte uploads disabled in hosted mode", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn upload_artifact(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    require_scope(&ctx, "artifacts:write", &state)?;
    if !state.config.artifact_uploads_enabled {
        return Err(AppError::forbidden(
            "artifact byte uploads are disabled until hosted object storage is configured",
        ));
    }
    let run_id = parse_uuid(&run_id, "run not found")?;
    let input =
        read_json::<UploadArtifactRequest>(&headers, bytes, state.config.max_upload_body_bytes)?;
    Ok(Json(
        json!({ "artifact": store::upload_artifact(&state.store, &state.config, &ctx, run_id, input).await? }),
    ))
}

#[utoipa::path(
    get,
    path = "/api/runs/{run_id}/artifacts",
    tag = "runs",
    params(
        ("run_id" = String, Path, description = "Run UUID"),
        ("limit" = Option<i64>, Query, description = "Page size"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Artifact rows for the run", body = super::openapi::ArtifactsEnvelope),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Run not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_artifacts(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(run_id): Path<String>,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    let run_id = parse_uuid(&run_id, "run not found")?;
    Ok(Json(
        json!({ "artifacts": store::list_artifacts(&state.store, &ctx, run_id, &query).await? }),
    ))
}

#[utoipa::path(
    get,
    path = "/api/artifacts/{artifact_id}/download",
    tag = "runs",
    params(
        ("artifact_id" = String, Path, description = "Artifact UUID"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Artifact byte stream", content_type = "application/octet-stream"),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 404, description = "Artifact not found", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn download_artifact(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(artifact_id): Path<String>,
) -> AppResult<Response> {
    let ctx = context(&state, &headers, true).await?;
    let artifact_id = parse_uuid(&artifact_id, "artifact not found")?;
    let artifact = store::get_artifact_for_context(&state.store, &ctx, artifact_id).await?;
    let artifact_store = LocalArtifactStore::new(&state.config.artifact_root);
    let file = artifact_store.open(&artifact).await?;
    let content_type = artifact
        .mime_type
        .unwrap_or_else(|| "application/octet-stream".to_string());
    let mut response = Response::new(Body::from_stream(ReaderStream::new(file)));
    response
        .headers_mut()
        .insert(header::CONTENT_TYPE, header_value(&content_type)?);
    if let Some(size_bytes) = artifact.size_bytes {
        response.headers_mut().insert(
            header::CONTENT_LENGTH,
            header_value(&size_bytes.to_string())?,
        );
    }
    Ok(response)
}

#[utoipa::path(
    get,
    path = "/api/export",
    tag = "runs",
    params(
        ("project" = Option<String>, Query, description = "Filter by project name"),
        ("status" = Option<String>, Query, description = "Filter by run status"),
        ("q" = Option<String>, Query, description = "Substring search"),
        ("sort_by" = Option<String>, Query, description = "Sort key"),
        ("metric_key" = Option<String>, Query, description = "Metric key for export columns"),
    ),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Versioned export payload", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Missing export scope", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn export_data(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Query(query): Query<HashMap<String, String>>,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    Ok(Json(store::export_data(&state.store, &ctx, &query).await?))
}

#[utoipa::path(
    get,
    path = "/api/usage",
    tag = "runs",
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Computed org usage summary", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Missing usage:read scope or restricted org access", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn usage_summary(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    require_scope(&ctx, "usage:read", &state)?;
    Ok(Json(store::usage_summary(&state.store, &ctx).await?))
}

#[utoipa::path(
    get,
    path = "/api/usage/export",
    tag = "runs",
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Versioned usage export payload", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Missing usage:read scope or restricted org access", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn usage_export(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    require_scope(&ctx, "usage:read", &state)?;
    Ok(Json(store::usage_export(&state.store, &ctx).await?))
}

#[utoipa::path(
    get,
    path = "/api/imports",
    tag = "runs",
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Recent imports for the caller's tenant", body = super::openapi::JsonObjectResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn list_imports(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    Ok(Json(store::list_imports(&state.store, &ctx).await?))
}

#[utoipa::path(
    post,
    path = "/api/imports/neptune",
    tag = "runs",
    params(
        ("dry_run" = Option<bool>, Query, description = "Run validation only without persisting"),
    ),
    request_body(content = super::openapi::JsonObjectResponse, description = "Normalized Neptune JSON payload"),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Dry-run or completed import summary", body = super::openapi::JsonObjectResponse),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Missing imports:write scope", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn import_neptune(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Query(query): Query<HashMap<String, String>>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    import_with_source(state, headers, query, bytes, "neptune").await
}

#[utoipa::path(
    post,
    path = "/api/imports/wandb",
    tag = "runs",
    params(
        ("dry_run" = Option<bool>, Query, description = "Run validation only without persisting"),
    ),
    request_body(content = super::openapi::JsonObjectResponse, description = "Normalized W&B JSON payload"),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Dry-run or completed import summary", body = super::openapi::JsonObjectResponse),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Missing imports:write scope", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn import_wandb(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Query(query): Query<HashMap<String, String>>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    import_with_source(state, headers, query, bytes, "wandb").await
}

#[utoipa::path(
    post,
    path = "/api/imports/mlflow",
    tag = "runs",
    params(
        ("dry_run" = Option<bool>, Query, description = "Run validation only without persisting"),
    ),
    request_body(content = super::openapi::JsonObjectResponse, description = "Normalized MLflow JSON payload"),
    security(("bearerApiKey" = []), ("browserSession" = [])),
    responses(
        (status = 200, description = "Dry-run or completed import summary", body = super::openapi::JsonObjectResponse),
        (status = 400, description = "Validation error", body = super::openapi::ErrorResponse),
        (status = 401, description = "Authentication required", body = super::openapi::ErrorResponse),
        (status = 403, description = "Missing imports:write scope", body = super::openapi::ErrorResponse),
    ),
)]
pub(super) async fn import_mlflow(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Query(query): Query<HashMap<String, String>>,
    bytes: Bytes,
) -> AppResult<Json<Value>> {
    import_with_source(state, headers, query, bytes, "mlflow").await
}

async fn import_with_source(
    state: Arc<AppState>,
    headers: HeaderMap,
    query: HashMap<String, String>,
    bytes: Bytes,
    source: &str,
) -> AppResult<Json<Value>> {
    let ctx = context(&state, &headers, true).await?;
    validate_session_mutation_origin(&state, &headers, &ctx)?;
    require_scope(&ctx, "imports:write", &state)?;
    let raw = read_json_value(&headers, bytes, state.config.max_body_bytes)?;
    let dry_run = query
        .get("dry_run")
        .map(|value| value == "true")
        .unwrap_or(false);
    Ok(Json(
        store::import_payload(&state.store, &ctx, source, dry_run, raw).await?,
    ))
}

pub(super) async fn not_found() -> AppError {
    AppError::not_found("route not found")
}

fn require_bootstrap(state: &AppState, headers: &HeaderMap) -> AppResult<()> {
    if !state.config.auth_mode.requires_api_key() {
        return Ok(());
    }
    require_strict_bootstrap(state, headers)
}

fn require_strict_bootstrap(state: &AppState, headers: &HeaderMap) -> AppResult<()> {
    if state.config.bootstrap_token.is_empty() {
        return Err(AppError::unauthorized("bootstrap token is not configured"));
    }
    match header_text(headers, "x-instantml-bootstrap-token") {
        Some(token) if token == state.config.bootstrap_token => Ok(()),
        _ => Err(AppError::unauthorized("invalid bootstrap token")),
    }
}

async fn require_admin_or_bootstrap(
    state: &AppState,
    headers: &HeaderMap,
    org_id: Uuid,
) -> AppResult<()> {
    if require_strict_bootstrap(state, headers).is_ok() {
        return Ok(());
    }
    if header_text(headers, "authorization").is_some() {
        let ctx = context(state, headers, true).await?;
        if ctx.org_id != org_id {
            return Err(AppError::forbidden(
                "organization belongs to a different API key",
            ));
        }
        require_scope(&ctx, "api_keys:write", state)?;
        return store::require_unrestricted_org_access(&ctx);
    }
    if state.config.auth_mode.requires_api_key() && session_cookie(headers).is_none() {
        require_strict_bootstrap(state, headers)?;
        return Ok(());
    }
    let session = session_context(state, headers).await?;
    if session.organization.id != org_id {
        return Err(AppError::forbidden(
            "session belongs to a different organization",
        ));
    }
    store::require_org_admin(&state.store, session.user.id, org_id)
        .await
        .map(|_| ())
}

async fn admin_actor(
    state: &AppState,
    headers: &HeaderMap,
    org_id: Uuid,
) -> AppResult<Option<Uuid>> {
    if require_strict_bootstrap(state, headers).is_ok() {
        return Ok(None);
    }
    if header_text(headers, "authorization").is_some() {
        let ctx = context(state, headers, true).await?;
        if ctx.org_id != org_id {
            return Err(AppError::forbidden(
                "organization belongs to a different API key",
            ));
        }
        require_scope(&ctx, "api_keys:write", state)?;
        store::require_unrestricted_org_access(&ctx)?;
        return Ok(None);
    }
    if state.config.auth_mode.requires_api_key() && session_cookie(headers).is_none() {
        require_strict_bootstrap(state, headers)?;
        return Ok(None);
    }
    validate_mutation_origin(state, headers)?;
    let session = session_context(state, headers).await?;
    if session.organization.id != org_id {
        return Err(AppError::forbidden(
            "session belongs to a different organization",
        ));
    }
    if store::is_shared_demo_org(&session.organization) {
        return Err(AppError::forbidden(
            "demo workspace browser sessions are read-only",
        ));
    }
    store::require_org_admin(&state.store, session.user.id, org_id).await?;
    Ok(Some(session.user.id))
}

async fn reject_demo_session_mutation(state: &AppState, headers: &HeaderMap) -> AppResult<()> {
    let session = session_context(state, headers).await?;
    if store::is_shared_demo_org(&session.organization) {
        return Err(AppError::forbidden(
            "demo workspace browser sessions are read-only",
        ));
    }
    Ok(())
}

async fn context(
    state: &AppState,
    headers: &HeaderMap,
    tenant_route: bool,
) -> AppResult<RequestContext> {
    // Tier 2: the data plane no longer refreshes control state on every
    // request. A background task (spawned in `serve()` for the data plane)
    // keeps the in-memory projection fresh out-of-band, so the request hot
    // path makes zero control-plane queries. Worst-case staleness is bounded
    // by `CONTROL_REFRESH_BACKGROUND_INTERVAL` (see store::mod).
    let ctx = match header_text(headers, "authorization") {
        Some(header) => {
            let token = header
                .strip_prefix("Bearer ")
                .or_else(|| header.strip_prefix("bearer "))
                .ok_or_else(|| AppError::unauthorized("authorization must use bearer token"))?;
            let auth = store::authenticate_api_key(&state.store, token).await?;
            RequestContext {
                org_id: auth.org_id,
                auth: Some(auth),
                session: None,
            }
        }
        None => {
            let Some(token) = session_cookie(headers) else {
                if state.config.auth_mode.requires_api_key() && tenant_route {
                    return Err(AppError::unauthorized("missing bearer token"));
                }
                return Ok(RequestContext::local());
            };
            let payload = store::authenticate_session(&state.store, token).await?;
            RequestContext {
                org_id: payload.organization.id,
                auth: None,
                session: Some(SessionContext {
                    session_id: payload.session.id,
                    user_id: payload.user.id,
                    role: payload.membership.role,
                    demo_read_only: store::is_shared_demo_org(&payload.organization),
                }),
            }
        }
    };
    if tenant_route {
        state.store.ensure_tenant_loaded(ctx.org_id).await?;
    }
    Ok(ctx)
}

fn require_scope(ctx: &RequestContext, scope: &str, state: &AppState) -> AppResult<()> {
    if let Some(auth) = &ctx.auth {
        return auth.require_scope(scope);
    }
    if let Some(session) = &ctx.session {
        return require_session_scope(session, scope);
    }
    if state.config.auth_mode.requires_api_key() {
        return Err(AppError::unauthorized("missing bearer token"));
    }
    Ok(())
}

fn require_session_scope(session: &SessionContext, scope: &str) -> AppResult<()> {
    if session.demo_read_only {
        return if scope == "export:read" {
            Ok(())
        } else {
            Err(AppError::forbidden(
                "demo workspace browser sessions are read-only",
            ))
        };
    }
    let role = session.role.as_str();
    let allowed = match scope {
        "sdk:ingest" | "artifacts:write" => matches!(role, "owner" | "admin" | "member"),
        "imports:write" | "usage:read" | "api_keys:write" => matches!(role, "owner" | "admin"),
        "export:read" => matches!(role, "owner" | "admin" | "member" | "viewer"),
        _ => false,
    };
    if allowed {
        Ok(())
    } else {
        Err(AppError::forbidden(format!(
            "session role requires permission {scope}"
        )))
    }
}

async fn session_context(
    state: &AppState,
    headers: &HeaderMap,
) -> AppResult<crate::domain::AuthSessionPayload> {
    let token = session_cookie(headers).ok_or_else(|| AppError::unauthorized("missing session"))?;
    store::authenticate_session(&state.store, token).await
}

fn session_cookie(headers: &HeaderMap) -> Option<&str> {
    cookie_value(headers, SESSION_COOKIE)
}

fn cookie_value<'a>(headers: &'a HeaderMap, cookie_name: &str) -> Option<&'a str> {
    let raw = header_text(headers, "cookie")?;
    raw.split(';').find_map(|part| {
        let (name, value) = part.trim().split_once('=')?;
        (name == cookie_name && !value.is_empty()).then_some(value)
    })
}

fn json_with_session_cookie<T: serde::Serialize>(
    state: &AppState,
    headers: &HeaderMap,
    payload: T,
    token: &str,
) -> AppResult<Response> {
    let mut response = Json(payload).into_response();
    response.headers_mut().append(
        header::SET_COOKIE,
        header_value(&session_cookie_header(
            token,
            is_secure_request(state, headers),
        ))?,
    );
    Ok(response)
}

fn session_cookie_header(token: &str, secure: bool) -> String {
    let secure = if secure { "; Secure" } else { "" };
    format!(
        "{SESSION_COOKIE}={token}; Path=/; HttpOnly; SameSite=Lax; Max-Age={SESSION_COOKIE_MAX_AGE_SECS}"
    ) + secure
}

fn clear_session_cookie() -> String {
    format!("{SESSION_COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0")
}

fn is_secure_request(state: &AppState, headers: &HeaderMap) -> bool {
    if let Some(proto) = header_text(headers, "x-forwarded-proto") {
        return proto.eq_ignore_ascii_case("https");
    }
    // Without an explicit forwarded-proto, fall back to topology heuristics.
    // The bind address may be 0.0.0.0 inside a container even when the client
    // reached us via http://localhost:PORT — using the request's Host header
    // catches that case so we don't set `Secure` on cookies the browser will
    // then refuse to send back.
    let host_is_loopback = header_text(headers, "host")
        .map(|host| {
            let bare = host.split(':').next().unwrap_or(host);
            matches!(bare, "localhost" | "127.0.0.1" | "::1" | "[::1]")
        })
        .unwrap_or(false);
    if host_is_loopback {
        return false;
    }
    !state.config.bind_addr.ip().is_loopback()
}

fn validate_mutation_origin(state: &AppState, headers: &HeaderMap) -> AppResult<()> {
    validate_mutation_origin_inner(state, headers, state.config.auth_mode.requires_api_key())
}

fn validate_mutation_origin_required(state: &AppState, headers: &HeaderMap) -> AppResult<()> {
    validate_mutation_origin_inner(state, headers, true)
}

fn validate_session_mutation_origin(
    state: &AppState,
    headers: &HeaderMap,
    ctx: &RequestContext,
) -> AppResult<()> {
    if ctx.session.is_some() {
        validate_mutation_origin(state, headers)?;
    }
    Ok(())
}

fn validate_mutation_origin_inner(
    state: &AppState,
    headers: &HeaderMap,
    require_origin: bool,
) -> AppResult<()> {
    let Some(origin) = header_text(headers, "origin") else {
        return if require_origin {
            Err(AppError::forbidden("origin is required for this request"))
        } else {
            Ok(())
        };
    };
    let origin = origin.trim_end_matches('/');
    if state
        .config
        .allowed_frontend_origins
        .iter()
        .any(|allowed| allowed == origin)
    {
        return Ok(());
    }
    if request_origin(state, headers).as_deref() == Some(origin) {
        return Ok(());
    }
    if let Ok(url) = Url::parse(origin) {
        if url
            .host_str()
            .is_some_and(|host| matches!(host, "localhost" | "127.0.0.1" | "::1"))
        {
            return Ok(());
        }
    }
    Err(AppError::forbidden(
        "origin is not allowed for this request",
    ))
}

fn request_origin(state: &AppState, headers: &HeaderMap) -> Option<String> {
    let host = header_text(headers, "host")?;
    let scheme = if is_secure_request(state, headers) {
        "https"
    } else {
        "http"
    };
    Some(format!("{scheme}://{host}"))
}

fn read_json<T: DeserializeOwned>(
    headers: &HeaderMap,
    bytes: Bytes,
    max_bytes: usize,
) -> AppResult<T> {
    validate_json_body(headers, &bytes, max_bytes)?;
    serde_json::from_slice::<T>(&bytes)
        .map_err(|_| AppError::validation("request body must be valid JSON"))
}

fn read_json_value(headers: &HeaderMap, bytes: Bytes, max_bytes: usize) -> AppResult<Value> {
    validate_json_body(headers, &bytes, max_bytes)?;
    let raw: Value = serde_json::from_slice(&bytes)
        .map_err(|_| AppError::validation("request body must be valid JSON"))?;
    if !raw.is_object() {
        return Err(AppError::validation("request body must be a JSON object"));
    }
    Ok(raw)
}

fn read_json_with_raw<T: DeserializeOwned>(
    headers: &HeaderMap,
    bytes: Bytes,
    max_bytes: usize,
) -> AppResult<(T, Value)> {
    let raw = read_json_value(headers, bytes, max_bytes)?;
    let typed = serde_json::from_value::<T>(raw.clone())
        .map_err(|_| AppError::validation("request body must be valid JSON"))?;
    Ok((typed, raw))
}

fn validate_json_body(headers: &HeaderMap, bytes: &Bytes, max_bytes: usize) -> AppResult<()> {
    if bytes.len() > max_bytes {
        return Err(AppError::payload_too_large("request body is too large"));
    }
    if let Some(length) = header_text(headers, "content-length") {
        let length = length
            .parse::<usize>()
            .map_err(|_| AppError::validation("invalid content-length"))?;
        if length > max_bytes {
            return Err(AppError::payload_too_large("request body is too large"));
        }
    }
    let content_type = header_text(headers, "content-type").unwrap_or_default();
    if !content_type.contains("application/json") {
        return Err(AppError::validation(
            "content-type must be application/json",
        ));
    }
    Ok(())
}

fn validate_clerk_signup_allowed(
    config: &AppConfig,
    email: &str,
    input: &ClerkAuthRequest,
) -> AppResult<()> {
    if !is_clerk_signup_request(input) {
        return Ok(());
    }
    if config.signup_allowed_emails.is_empty() && config.signup_allowed_domains.is_empty() {
        return Ok(());
    }
    let normalized = email.trim().to_ascii_lowercase();
    if config
        .signup_allowed_emails
        .iter()
        .any(|allowed| allowed == &normalized)
    {
        return Ok(());
    }
    let domain = normalized.split_once('@').map(|(_, domain)| domain);
    if let Some(domain) = domain {
        if config
            .signup_allowed_domains
            .iter()
            .any(|allowed| allowed == domain)
        {
            return Ok(());
        }
    }
    Err(AppError::forbidden(
        "hosted signup is restricted to invited accounts",
    ))
}

fn is_clerk_signup_request(input: &ClerkAuthRequest) -> bool {
    input.mode.as_deref() == Some("signup")
        || input
            .org_name
            .as_deref()
            .is_some_and(|name| !name.trim().is_empty())
}

fn header_text<'a>(headers: &'a HeaderMap, name: &str) -> Option<&'a str> {
    headers.get(name).and_then(|value| value.to_str().ok())
}

fn parse_uuid(raw: &str, missing_message: &str) -> AppResult<Uuid> {
    Uuid::parse_str(raw).map_err(|_| AppError::not_found(missing_message))
}

fn header_value(value: &str) -> AppResult<HeaderValue> {
    HeaderValue::from_str(value).map_err(|_| AppError::internal("invalid header value"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn session(role: &str, demo_read_only: bool) -> SessionContext {
        SessionContext {
            session_id: Uuid::new_v4(),
            user_id: Uuid::new_v4(),
            role: role.to_string(),
            demo_read_only,
        }
    }

    #[test]
    fn demo_browser_sessions_are_read_only() {
        let demo = session("owner", true);
        assert!(require_session_scope(&demo, "export:read").is_ok());
        for scope in [
            "sdk:ingest",
            "artifacts:write",
            "imports:write",
            "usage:read",
            "api_keys:write",
        ] {
            assert!(require_session_scope(&demo, scope).is_err());
        }
    }

    #[test]
    fn non_demo_session_roles_keep_expected_write_permissions() {
        assert!(require_session_scope(&session("member", false), "sdk:ingest").is_ok());
        assert!(require_session_scope(&session("member", false), "api_keys:write").is_err());
        assert!(require_session_scope(&session("owner", false), "api_keys:write").is_ok());
    }

    #[test]
    fn openapi_paths_follow_service_plane_roles() {
        use crate::config::ServicePlaneRole;

        assert!(openapi_path_available_for_plane(
            "/api/auth/config",
            ServicePlaneRole::Control
        ));
        assert!(openapi_path_available_for_plane(
            "/api/auth/config",
            ServicePlaneRole::Data
        ));
        assert!(openapi_path_available_for_plane(
            "/api/orgs/{org_id}/api-keys",
            ServicePlaneRole::Control
        ));
        assert!(!openapi_path_available_for_plane(
            "/api/orgs/{org_id}/api-keys",
            ServicePlaneRole::Data
        ));
        assert!(openapi_path_available_for_plane(
            "/runs",
            ServicePlaneRole::Data
        ));
        assert!(!openapi_path_available_for_plane(
            "/runs",
            ServicePlaneRole::Control
        ));
    }

    #[test]
    fn utoipa_apidoc_emits_annotated_paths_and_schemas() {
        use utoipa::OpenApi as _;
        let spec = crate::http::openapi::ApiDoc::openapi();
        let value = serde_json::to_value(&spec).expect("serialize spec");
        let paths = value
            .get("paths")
            .and_then(Value::as_object)
            .expect("paths");
        // Every router-registered path (minus /healthz alias, /metrics
        // Prometheus text, and /openapi.json self-reference) must be present
        // in the utoipa-generated spec. Update this list when you add or
        // remove routes.
        for expected in [
            // platform
            "/health",
            "/readyz",
            // auth
            "/api/auth/config",
            "/api/auth/dev/google",
            "/api/auth/clerk",
            "/api/auth/session",
            "/api/auth/logout",
            "/api/auth/switch-organization",
            "/api/auth/device-code/start",
            "/api/auth/device-code/poll",
            "/api/auth/device-code/confirm",
            // dashboard
            "/api/dashboard/preferences",
            "/api/workspace-views",
            "/api/workspace-views/{view_id}",
            // users / orgs
            "/api/users",
            "/api/orgs",
            "/api/orgs/memberships",
            "/api/orgs/name-availability",
            "/api/orgs/{org_id}/seats",
            "/api/orgs/{org_id}/api-keys",
            "/api/orgs/{org_id}/api-keys/{api_key_id}/revoke",
            "/api/orgs/{org_id}/service-accounts/{service_account_id}/disable",
            // runs core
            "/projects",
            "/runs",
            "/runs/{run_id}",
            "/runs/{run_id}/metrics",
            "/api/runs/{run_id}/logs",
            "/api/metrics/series",
            // dashboard analytics
            "/api/overview",
            "/api/runs/summary",
            "/api/runs/side-by-side",
            // attributes / objects
            "/api/runs/{run_id}/attributes",
            "/api/runs/{run_id}/objects",
            "/api/objects/{object_id}/rows",
            // artifacts
            "/api/runs/{run_id}/artifacts",
            "/api/runs/{run_id}/artifacts/upload",
            "/api/artifacts/{artifact_id}/download",
            // export / usage / imports
            "/api/export",
            "/api/usage",
            "/api/usage/export",
            "/api/imports",
            "/api/imports/neptune",
            "/api/imports/wandb",
            "/api/imports/mlflow",
        ] {
            assert!(
                paths.contains_key(expected),
                "utoipa spec missing path {expected}"
            );
        }
        let schemas = value
            .pointer("/components/schemas")
            .and_then(Value::as_object)
            .expect("components.schemas");
        for expected in [
            "RunRow",
            "ProjectRow",
            "SeatRow",
            "PublicApiKeyRow",
            "WorkspaceViewSummary",
            "AuthSessionPayload",
            "ProjectEnvelope",
            "RunsEnvelope",
            "InsertedEnvelope",
        ] {
            assert!(
                schemas.contains_key(expected),
                "utoipa spec missing schema {expected}"
            );
        }
    }

    #[test]
    fn clerk_signup_allowlist_only_applies_to_signup() {
        let mut config = test_config();
        config.signup_allowed_emails = vec!["founder@example.com".to_string()];
        config.signup_allowed_domains = vec!["instantml.ai".to_string()];
        let signup = ClerkAuthRequest {
            token: None,
            mode: Some("signup".to_string()),
            account_type: None,
            org_name: Some("Acme".to_string()),
            plan_tier: None,
            seat_emails: None,
            accept_invite_org_id: None,
        };
        assert!(validate_clerk_signup_allowed(&config, "founder@example.com", &signup).is_ok());
        assert!(validate_clerk_signup_allowed(&config, "teammate@instantml.ai", &signup).is_ok());
        assert!(validate_clerk_signup_allowed(&config, "stranger@example.org", &signup).is_err());

        let signin = ClerkAuthRequest {
            token: None,
            mode: Some("signin".to_string()),
            account_type: None,
            org_name: None,
            plan_tier: None,
            seat_emails: None,
            accept_invite_org_id: None,
        };
        assert!(validate_clerk_signup_allowed(&config, "stranger@example.org", &signin).is_ok());
    }

    fn test_config() -> AppConfig {
        AppConfig {
            clickhouse_url: "http://default:@127.0.0.1:8123/instantml".to_string(),
            bind_addr: "127.0.0.1:0".parse().unwrap(),
            service_plane: crate::config::ServicePlaneRole::Combined,
            max_body_bytes: 1_000_000,
            max_upload_body_bytes: 50_000_000,
            artifact_root: ".instantml/rust-artifacts".into(),
            bootstrap_token: String::new(),
            auth_mode: crate::config::AuthMode::Local,
            dev_auth_enabled: true,
            managed_clerk_enabled: false,
            clerk_secret_key: None,
            clerk_api_base: "https://api.clerk.com".to_string(),
            clerk_jwt_issuer: None,
            clerk_session_max_token_age: std::time::Duration::from_secs(600),
            signup_allowed_emails: Vec::new(),
            signup_allowed_domains: Vec::new(),
            artifact_uploads_enabled: true,
            allowed_frontend_origins: Vec::new(),
            request_timeout: std::time::Duration::from_secs(30),
            log_format: crate::config::LogFormat::Pretty,
            hosted_clickhouse: None,
            frontend_base_url: Some("http://localhost:3000".to_string()),
        }
    }

    #[test]
    fn org_switcher_endpoints_live_on_control_plane() {
        use crate::config::ServicePlaneRole;

        for path in ["/api/auth/switch-organization", "/api/orgs/memberships"] {
            assert!(
                openapi_path_available_for_plane(path, ServicePlaneRole::Control),
                "{path} should be available on control plane"
            );
            assert!(
                openapi_path_available_for_plane(path, ServicePlaneRole::Combined),
                "{path} should be available on combined plane"
            );
            assert!(
                !openapi_path_available_for_plane(path, ServicePlaneRole::Data),
                "{path} should not be available on data plane"
            );
        }
    }

    #[test]
    fn device_code_endpoints_on_control_plane() {
        use crate::config::ServicePlaneRole;

        for path in [
            "/api/auth/device-code/start",
            "/api/auth/device-code/poll",
            "/api/auth/device-code/confirm",
        ] {
            assert!(
                openapi_path_available_for_plane(path, ServicePlaneRole::Control),
                "{path} should be available on control plane"
            );
            assert!(
                openapi_path_available_for_plane(path, ServicePlaneRole::Combined),
                "{path} should be available on combined plane"
            );
            assert!(
                !openapi_path_available_for_plane(path, ServicePlaneRole::Data),
                "{path} should not be available on data plane"
            );
        }
    }

    #[test]
    fn frontend_base_url_fallback_chain() {
        // Test that the config's frontend_base_url is used when set.
        let config = test_config();
        let url = config
            .frontend_base_url
            .as_deref()
            .or_else(|| config.allowed_frontend_origins.first().map(String::as_str))
            .unwrap_or("http://localhost:3000");
        assert_eq!(url, "http://localhost:3000");
    }

    #[test]
    fn frontend_base_url_falls_back_to_allowed_origins() {
        let mut config = test_config();
        config.frontend_base_url = None;
        config.allowed_frontend_origins = vec!["https://app.example.com".to_string()];
        let url = config
            .frontend_base_url
            .as_deref()
            .or_else(|| config.allowed_frontend_origins.first().map(String::as_str))
            .unwrap_or("http://localhost:3000");
        assert_eq!(url, "https://app.example.com");
    }

    #[test]
    fn frontend_base_url_falls_back_to_localhost_when_nothing_set() {
        let mut config = test_config();
        config.frontend_base_url = None;
        config.allowed_frontend_origins = vec![];
        let url = config
            .frontend_base_url
            .as_deref()
            .or_else(|| config.allowed_frontend_origins.first().map(String::as_str))
            .unwrap_or("http://localhost:3000");
        assert_eq!(url, "http://localhost:3000");
    }
}
