//! LLM summary backing for `LLMSummaryBlock`.
//!
//! The provider call is gated on `INSTANTML_LLM_PROVIDER` + the appropriate
//! API key env var. Without a key, the stub provider returns a deterministic
//! placeholder so the pipeline stays exercised in tests, local dev, and the
//! pilot rollout — we ship the wiring and flip the real provider on once an
//! API key lands in production secrets.

use super::*;

use std::env;

use serde::Serialize;

const STUB_PLACEHOLDER: &str =
    "LLM summary unavailable: configure ANTHROPIC_API_KEY (or set INSTANTML_LLM_PROVIDER=stub for deterministic output).";

/// Snapshot of a single run's metric aggregates passed to the LLM. We
/// deliberately stay at summary granularity — count/min/max/mean/latest —
/// rather than streaming raw points, both for cost and because the LLM
/// reasoning over aggregates is sharper than over noisy sample series.
#[derive(Clone, Debug, Serialize)]
pub struct LlmRunMetricSummary {
    pub run_id: String,
    pub run_name: String,
    pub project: String,
    pub metrics: Vec<LlmMetricAggregate>,
}

#[derive(Clone, Debug, Serialize)]
pub struct LlmMetricAggregate {
    pub key: String,
    pub count: i64,
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub mean: Option<f64>,
    pub latest: Option<f64>,
}

/// Input to the provider. `angle` is the user-selected framing
/// (what-worked / outliers / config-diffs / next-steps / free-form). The
/// `custom_prompt` is appended after the angle preamble when present.
#[derive(Clone, Debug, Serialize)]
pub struct LlmSummaryRequest {
    pub angle: String,
    pub custom_prompt: Option<String>,
    pub report_title: String,
    pub runs: Vec<LlmRunMetricSummary>,
}

/// Provider identity that backed the summary. Stored alongside the generated
/// text on the block so future regenerations can be conditional on provider
/// changes, and so the UI can show "generated by stub" badges.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ReportLlmProvider {
    /// Deterministic stub used when no API key is configured.
    Stub,
    /// Anthropic Claude provider. The actual network call is intentionally
    /// not implemented in v1 — we ship the wiring and the env var gating
    /// only. See `generate_summary` for the punt-to-stub behavior.
    Anthropic,
}

pub fn report_llm_provider_label(provider: ReportLlmProvider) -> &'static str {
    match provider {
        ReportLlmProvider::Stub => "stub",
        ReportLlmProvider::Anthropic => "anthropic",
    }
}

fn resolve_provider() -> ReportLlmProvider {
    match env::var("INSTANTML_LLM_PROVIDER")
        .ok()
        .map(|value| value.trim().to_ascii_lowercase())
        .as_deref()
    {
        Some("anthropic") => ReportLlmProvider::Anthropic,
        Some("stub") => ReportLlmProvider::Stub,
        // Auto-detect: if an Anthropic key is configured, use Anthropic;
        // otherwise stub.
        _ => {
            if env::var("ANTHROPIC_API_KEY")
                .ok()
                .filter(|value| !value.trim().is_empty())
                .is_some()
            {
                ReportLlmProvider::Anthropic
            } else {
                ReportLlmProvider::Stub
            }
        }
    }
}

/// Build the summary paragraph. Returns the generated text plus the provider
/// that produced it.
pub fn generate_summary(request: &LlmSummaryRequest) -> AppResult<(String, ReportLlmProvider)> {
    let provider = resolve_provider();
    match provider {
        ReportLlmProvider::Stub => Ok((stub_summary(request), provider)),
        ReportLlmProvider::Anthropic => {
            // V1 ships the wiring only; the actual network call lands in
            // v1.5 once we have a vetted secret store and rate-limit budget.
            // Until then, when the key is set we still return a slightly
            // different placeholder so deployments know the env was picked
            // up.
            if env::var("ANTHROPIC_API_KEY")
                .ok()
                .filter(|value| !value.trim().is_empty())
                .is_some()
            {
                Ok((anthropic_placeholder(request), ReportLlmProvider::Anthropic))
            } else {
                Err(AppError::internal(
                    "INSTANTML_LLM_PROVIDER=anthropic requires ANTHROPIC_API_KEY",
                ))
            }
        }
    }
}

fn stub_summary(request: &LlmSummaryRequest) -> String {
    if request.runs.is_empty() {
        return STUB_PLACEHOLDER.to_string();
    }
    let run_count = request.runs.len();
    let metric_count = request
        .runs
        .iter()
        .map(|run| run.metrics.len())
        .sum::<usize>();
    format!(
        "{STUB_PLACEHOLDER}\n\nIn the meantime: this summary would cover {run_count} run(s) across {metric_count} metric aggregate(s) with angle `{}`.",
        request.angle
    )
}

fn anthropic_placeholder(request: &LlmSummaryRequest) -> String {
    let run_count = request.runs.len();
    format!(
        "(Anthropic provider wired but live calls deferred to v1.5.) Angle `{}` over {run_count} run(s) for `{}`.",
        request.angle, request.report_title
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    /// Provider resolution reads from process env, which other tests might
    /// also touch. Serialize the env-mutating tests behind a local mutex so
    /// they don't race when `cargo test` parallelizes.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    fn sample_request() -> LlmSummaryRequest {
        LlmSummaryRequest {
            angle: "what-worked".to_string(),
            custom_prompt: None,
            report_title: "Ablation".to_string(),
            runs: vec![LlmRunMetricSummary {
                run_id: "run-1".to_string(),
                run_name: "exp-a".to_string(),
                project: "proj-a".to_string(),
                metrics: vec![LlmMetricAggregate {
                    key: "loss".to_string(),
                    count: 10,
                    min: Some(0.1),
                    max: Some(0.9),
                    mean: Some(0.4),
                    latest: Some(0.2),
                }],
            }],
        }
    }

    fn clear_env() {
        std::env::remove_var("INSTANTML_LLM_PROVIDER");
        std::env::remove_var("ANTHROPIC_API_KEY");
    }

    #[test]
    fn stub_provider_without_keys_returns_placeholder() {
        let _guard = ENV_LOCK.lock().unwrap();
        clear_env();
        let (text, provider) = generate_summary(&sample_request()).expect("stub ok");
        assert_eq!(provider, ReportLlmProvider::Stub);
        assert!(text.contains("LLM summary unavailable"));
        assert!(text.contains("what-worked"));
    }

    #[test]
    fn anthropic_provider_requires_api_key() {
        let _guard = ENV_LOCK.lock().unwrap();
        clear_env();
        std::env::set_var("INSTANTML_LLM_PROVIDER", "anthropic");
        let err = generate_summary(&sample_request()).unwrap_err();
        assert!(err.message().contains("ANTHROPIC_API_KEY"));
        clear_env();
    }

    #[test]
    fn anthropic_provider_uses_key_when_present() {
        let _guard = ENV_LOCK.lock().unwrap();
        clear_env();
        std::env::set_var("INSTANTML_LLM_PROVIDER", "anthropic");
        std::env::set_var("ANTHROPIC_API_KEY", "sk-test");
        let (text, provider) = generate_summary(&sample_request()).expect("anthropic placeholder");
        assert_eq!(provider, ReportLlmProvider::Anthropic);
        assert!(text.contains("Anthropic provider wired"));
        assert!(text.contains("Ablation"));
        clear_env();
    }

    #[test]
    fn provider_label_round_trips() {
        assert_eq!(report_llm_provider_label(ReportLlmProvider::Stub), "stub");
        assert_eq!(
            report_llm_provider_label(ReportLlmProvider::Anthropic),
            "anthropic"
        );
    }
}
