/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_orgs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{org_id}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_api_keys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{org_id}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_seats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_projects"];
        put?: never;
        post: operations["create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_runs"];
        put?: never;
        post: operations["create_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_run"];
        trace?: never;
    };
    "/runs/{run_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["log_metrics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiKeysEnvelope: {
            api_keys: components["schemas"]["PublicApiKeyRow"][];
        };
        ArtifactRow: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            metadata: Record<string, never>;
            mime_type?: string | null;
            name: string;
            /** Format: uuid */
            org_id: string;
            /** Format: uuid */
            run_id: string;
            sha256?: string | null;
            /** Format: int64 */
            size_bytes?: number | null;
            /** Format: double */
            step?: number | null;
            storage_backend: string;
            storage_key?: string | null;
            storage_path?: string | null;
            type: string;
            uri: string;
        };
        AttributeInput: {
            /** Format: uuid */
            artifact_id?: string | null;
            path: string;
            step?: Record<string, never> | null;
            summary?: Record<string, never> | null;
            timestamp?: string | null;
            type: string;
            value: Record<string, never>;
        };
        AttributeRow: {
            /** Format: uuid */
            artifact_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            logged_at?: string | null;
            /** Format: uuid */
            org_id: string;
            path: string;
            /** Format: uuid */
            run_id: string;
            /** Format: double */
            step?: number | null;
            summary: Record<string, never>;
            type: string;
            value: Record<string, never>;
        };
        AuthConfigResponse: {
            dev_auth_enabled: boolean;
            managed_clerk_enabled: boolean;
        };
        AuthSessionPayload: {
            account_type: string;
            authenticated: boolean;
            membership: components["schemas"]["MembershipRow"];
            memberships: components["schemas"]["MembershipRow"][];
            organization: components["schemas"]["OrganizationRow"];
            provisioning?: null | components["schemas"]["ProvisioningStatusPayload"];
            session: components["schemas"]["UserSessionRow"];
            user: components["schemas"]["UserRow"];
        };
        AuthSessionUnauthenticated: {
            authenticated: boolean;
        };
        ClerkAuthRequest: {
            /** Format: uuid */
            accept_invite_org_id?: string | null;
            account_type?: string | null;
            mode?: string | null;
            org_name?: string | null;
            plan_tier?: string | null;
            seat_emails?: string[] | null;
            token?: string | null;
        };
        ConsoleLogInput: {
            /** Format: int64 */
            line_number?: number | null;
            message?: string | null;
            timestamp?: string | null;
        };
        ConsoleLogLine: {
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            line_number: number;
            message: string;
            /** Format: uuid */
            run_id: string;
            stream: string;
            /** Format: date-time */
            timestamp: string;
        };
        CreateApiKeyRequest: {
            /** Format: uuid */
            created_by_user_id?: string | null;
            expires_at?: string | null;
            name?: string | null;
            project?: string | null;
            /** Format: uuid */
            project_id?: string | null;
            scopes?: string[] | null;
        };
        CreateArtifactRequest: {
            metadata?: Record<string, never> | null;
            mime_type?: string | null;
            name?: string | null;
            path?: string | null;
            sha256?: string | null;
            size_bytes?: Record<string, never> | null;
            step?: Record<string, never> | null;
            type?: string | null;
            uri?: string | null;
        };
        CreateAttributesRequest: {
            attributes?: components["schemas"]["AttributeInput"][] | null;
            path?: string | null;
            step?: Record<string, never> | null;
            summary?: Record<string, never> | null;
            timestamp?: string | null;
            type?: string | null;
            value?: Record<string, never> | null;
        };
        CreateConsoleLogsRequest: {
            lines?: components["schemas"]["ConsoleLogInput"][] | null;
            stream?: string | null;
        };
        CreateObjectRequest: {
            /** Format: uuid */
            artifact_id?: string | null;
            key?: string | null;
            kind?: string | null;
            metadata?: Record<string, never> | null;
            rows?: Record<string, never> | null;
            step?: Record<string, never> | null;
            summary?: Record<string, never> | null;
            value?: Record<string, never> | null;
        };
        CreateOrganizationRequest: {
            name?: string | null;
            /** Format: uuid */
            owner_user_id?: string | null;
            plan_tier?: string | null;
            slug?: string | null;
        };
        CreateProjectRequest: {
            description?: string | null;
            name?: string | null;
        };
        CreateRunRequest: {
            config?: Record<string, never> | null;
            metadata?: Record<string, never> | null;
            name?: string | null;
            project?: string | null;
            tags?: string[] | null;
        };
        CreateUserRequest: {
            avatar_url?: string | null;
            display_name?: string | null;
            email?: string | null;
            email_verified?: boolean | null;
            primary_email?: string | null;
            provider?: string | null;
            provider_subject?: string | null;
        };
        DashboardPreferenceRow: {
            /** Format: uuid */
            org_id: string;
            /** Format: int32 */
            schema_version: number;
            selected_project?: string | null;
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            user_id?: string | null;
        };
        DashboardPreferencesEnvelope: {
            preferences: components["schemas"]["DashboardPreferenceRow"];
        };
        DevGoogleAuthRequest: {
            /** Format: uuid */
            accept_invite_org_id?: string | null;
            account_type?: string | null;
            display_name?: string | null;
            email?: string | null;
            mode?: string | null;
            org_name?: string | null;
            plan_tier?: string | null;
            seat_emails?: string[] | null;
        };
        DeviceCodeClientInfo: {
            name?: string | null;
            version?: string | null;
        };
        DeviceCodeConfirmRequest: {
            user_code?: string | null;
        };
        DeviceCodePollRequest: {
            device_code?: string | null;
        };
        DeviceCodeStartRequest: {
            client_info?: null | components["schemas"]["DeviceCodeClientInfo"];
        };
        ErrorBody: {
            code: string;
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        HealthResponse: {
            status: string;
        };
        InsertedEnvelope: {
            /** Format: int64 */
            inserted: number;
        };
        LogMetricsRequest: {
            metrics: Record<string, never>;
            preview?: boolean | null;
            preview_completion?: Record<string, never> | null;
            step: Record<string, never>;
            timestamp?: string | null;
        };
        MembershipRow: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            org_id: string;
            role: string;
            status: string;
            /** Format: uuid */
            user_id: string;
        };
        MetricPointRow: {
            /** Format: date-time */
            created_at: string;
            key: string;
            /** Format: double */
            step: number;
            /** Format: double */
            value: number;
        };
        MetricSeriesRow: {
            /** Format: double */
            best?: number | null;
            /** Format: double */
            best_step?: number | null;
            /** Format: int64 */
            count: number;
            key: string;
            /** Format: double */
            latest?: number | null;
            /** Format: double */
            latest_step?: number | null;
            /** Format: double */
            max?: number | null;
            /** Format: double */
            mean?: number | null;
            /** Format: double */
            min?: number | null;
            /** Format: uuid */
            run_id: string;
            /** Format: double */
            variance?: number | null;
        };
        OnboardingApiKey: {
            /** Format: uuid */
            id: string;
            plaintext: string;
            prefix: string;
        };
        OrganizationEnvelope: {
            organization: components["schemas"]["OrganizationRow"];
        };
        OrganizationRow: {
            account_type: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            created_by_user_id?: string | null;
            /** Format: uuid */
            id: string;
            name: string;
            plan_tier: string;
            /** Format: int32 */
            seat_limit: number;
            slug: string;
            /** @description Routing tier for this org's ClickHouse data plane.
             *     `"shared"` — routes to the shared cell (free/personal orgs).
             *     `"dedicated"` — routes to a per-org provisioned service.
             *     Older records that pre-date this field deserialize to `"dedicated"`
             *     (the safe fallback) via the serde default. */
            tenant_routing_tier?: string;
        };
        OrganizationsEnvelope: {
            organizations: components["schemas"]["OrganizationRow"][];
        };
        ProjectEnvelope: {
            project: components["schemas"]["ProjectRow"];
        };
        ProjectRow: {
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            org_id: string;
        };
        ProjectsEnvelope: {
            projects: components["schemas"]["ProjectRow"][];
        };
        ProvisioningStatusPayload: {
            mode: string;
            service_id?: string | null;
            status: string;
        };
        PublicApiKeyRow: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: uuid */
            id: string;
            key_prefix: string;
            /** Format: date-time */
            last_used_at?: string | null;
            name: string;
            /** Format: uuid */
            org_id: string;
            /** Format: uuid */
            project_id?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
            scopes: string[];
            /** Format: uuid */
            service_account_id: string;
        };
        ReserveSeatRequest: {
            email?: string | null;
            role?: string | null;
        };
        RunEnvelope: {
            run: components["schemas"]["RunRow"];
        };
        RunRow: {
            config: Record<string, never>;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: uuid */
            id: string;
            metadata: Record<string, never>;
            name: string;
            /** Format: uuid */
            org_id: string;
            project: string;
            /** Format: uuid */
            project_id: string;
            /** Format: date-time */
            started_at: string;
            status: string;
            tags: string[];
        };
        RunsEnvelope: {
            runs: components["schemas"]["RunRow"][];
        };
        SaveWorkspaceViewRequest: {
            name?: string | null;
            payload?: Record<string, never> | null;
            project?: string | null;
        };
        SeatEnvelope: {
            seat: components["schemas"]["SeatRow"];
        };
        SeatRow: {
            membership: components["schemas"]["MembershipRow"];
            user: components["schemas"]["SeatUserRow"];
        };
        SeatUserRow: {
            avatar_url?: string | null;
            display_name?: string | null;
            /** Format: uuid */
            id: string;
            primary_email: string;
        };
        SeatsEnvelope: {
            seats: components["schemas"]["SeatRow"][];
        };
        ServiceAccountRow: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            created_by_user_id?: string | null;
            /** Format: date-time */
            disabled_at?: string | null;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            org_id: string;
        };
        UpdateDashboardPreferencesRequest: {
            selected_project?: string | null;
        };
        UpdateRunRequest: {
            notes?: string | null;
            status?: string | null;
            tags?: string[] | null;
        };
        UploadArtifactRequest: {
            content_base64?: string | null;
            metadata?: Record<string, never> | null;
            mime_type?: string | null;
            name?: string | null;
            path?: string | null;
            step?: Record<string, never> | null;
            type?: string | null;
        };
        UserEnvelope: {
            user: components["schemas"]["UserRow"];
        };
        UserRow: {
            avatar_url?: string | null;
            /** Format: date-time */
            created_at: string;
            display_name?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_seen_at?: string | null;
            primary_email: string;
        };
        UserSessionRow: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_seen_at?: string | null;
            metadata: Record<string, never>;
            /** Format: uuid */
            org_id: string;
            /** Format: date-time */
            revoked_at?: string | null;
            /** Format: uuid */
            user_id: string;
        };
        UsersEnvelope: {
            users: components["schemas"]["UserRow"][];
        };
        WorkspaceViewEnvelope: {
            view: components["schemas"]["WorkspaceViewRow"];
        };
        WorkspaceViewRow: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            org_id: string;
            /** Format: uuid */
            owner_user_id?: string | null;
            payload: Record<string, never>;
            project?: string | null;
            /** Format: int32 */
            schema_version: number;
            /** Format: date-time */
            updated_at: string;
        };
        WorkspaceViewSummariesEnvelope: {
            views: components["schemas"]["WorkspaceViewSummary"][];
        };
        WorkspaceViewSummary: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            name: string;
            project?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Frontend auth provider availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfigResponse"];
                };
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionUnauthenticated"];
                };
            };
        };
    };
    auth_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unauthenticated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionUnauthenticated"];
                };
            };
        };
    };
    list_orgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of organizations visible to the caller */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationsEnvelope"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_api_keys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization UUID */
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API keys for the organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeysEnvelope"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_seats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization UUID */
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seats for the organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatsEnvelope"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects for the caller's organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsEnvelope"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Created or fetched project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEnvelope"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operational and metric stores ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: {
                /** @description Filter by project name */
                project?: string;
                /** @description Filter by run status */
                status?: string;
                /** @description Page size (1..=1000) */
                limit?: number;
                /** @description Offset for pagination */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsEnvelope"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Created run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEnvelope"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run UUID */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEnvelope"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run UUID */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRunRequest"];
            };
        };
        responses: {
            /** @description Updated run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEnvelope"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    log_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run UUID */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogMetricsRequest"];
            };
        };
        responses: {
            /** @description Inserted point count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsertedEnvelope"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
