use std::sync::Arc;

use axum::{
    extract::State,
    http::header,
    response::{IntoResponse, Response},
    Json,
};
use serde_json::{json, Value};

use crate::{
    errors::{AppError, AppResult},
    http::openapi::AuthConfigResponse,
    store,
};

use super::super::{observability, AppState};

#[utoipa::path(
    get,
    path = "/health",
    tag = "platform",
    security(),
    responses(
        (status = 200, description = "Service is healthy", body = crate::http::openapi::HealthResponse),
    ),
)]
pub async fn health() -> Json<Value> {
    Json(json!({ "status": "ok" }))
}

#[utoipa::path(
    get,
    path = "/readyz",
    tag = "platform",
    security(),
    responses(
        (status = 200, description = "Operational and metric stores ready", body = crate::http::openapi::HealthResponse),
        (status = 503, description = "Not ready", body = crate::http::openapi::ErrorResponse),
    ),
)]
pub async fn readyz(State(state): State<Arc<AppState>>) -> AppResult<Json<Value>> {
    if state.config.service_plane.includes_data() && !store::ready(&state.store).await {
        let reason = if !state.store.control_projection_health().await.loaded {
            "control projection is not loaded"
        } else {
            "clickhouse operational store is not ready"
        };
        let error = AppError::service_unavailable(reason);
        observability::readiness_failure(state.config.service_plane, "operational", &error);
        return Err(error);
    }
    if !state.config.service_plane.includes_data() && !store::control_ready(&state.store).await {
        let reason = if !state.store.control_projection_health().await.loaded {
            "control projection is not loaded"
        } else {
            "clickhouse control store is not ready"
        };
        let error = AppError::service_unavailable(reason);
        observability::readiness_failure(state.config.service_plane, "control", &error);
        return Err(error);
    }
    let projection = state.store.control_projection_health().await;
    Ok(Json(json!({
        "status": "ok",
        "control_projection_loaded": projection.loaded,
        "control_refresh_degraded": projection.refresh_degraded,
    })))
}

pub async fn metrics(State(state): State<Arc<AppState>>) -> Response {
    let projection = state.store.control_projection_health().await;
    let service_plane = state.config.service_plane.as_str();
    let body = format!(
        concat!(
            "instantml_rust_build_info{{service=\"rust-server\",service_plane=\"{}\"}} 1\n",
            "instantml_control_projection_loaded{{service_plane=\"{}\"}} {}\n",
            "instantml_control_refresh_degraded{{service_plane=\"{}\"}} {}\n",
        ),
        service_plane,
        service_plane,
        u8::from(projection.loaded),
        service_plane,
        u8::from(projection.refresh_degraded),
    );
    ([(header::CONTENT_TYPE, "text/plain; version=0.0.4")], body).into_response()
}

/// Serve the OpenAPI spec generated by utoipa from `#[utoipa::path]`
/// annotations on each handler. The response is filtered to only include
/// paths the active service plane actually serves.
pub async fn openapi_json(State(state): State<Arc<AppState>>) -> Json<Value> {
    use utoipa::OpenApi as _;
    let utoipa_spec = crate::http::openapi::ApiDoc::openapi();
    let service_plane = state.config.service_plane;
    let mut spec =
        serde_json::to_value(&utoipa_spec).expect("utoipa OpenApi is always JSON-serializable");
    if let Some(spec_obj) = spec.as_object_mut() {
        if let Some(Value::Object(paths)) = spec_obj.get_mut("paths") {
            paths.retain(|path, _| openapi_path_available_for_plane(path, service_plane));
        }
        spec_obj.insert(
            "x-instantml-service-plane".to_string(),
            json!(service_plane.as_str()),
        );
    }
    Json(spec)
}

pub fn openapi_path_available_for_plane(
    path: &str,
    service_plane: crate::config::ServicePlaneRole,
) -> bool {
    if matches!(
        path,
        "/health" | "/healthz" | "/readyz" | "/metrics" | "/openapi.json" | "/api/auth/config"
    ) {
        return true;
    }
    if path.starts_with("/api/auth/")
        || path == "/api/billing"
        || path.starts_with("/api/billing/")
        || path.starts_with("/api/admin/")
        || path == "/api/routing/current"
        || path == "/api/users"
        || path.starts_with("/api/invitations/")
        || path == "/api/orgs"
        || path == "/api/orgs/current-user"
        || path == "/api/orgs/memberships"
        || path == "/api/orgs/name-availability"
        || path == "/api/dashboard/preferences"
        || path == "/api/workspace-views"
        || path.starts_with("/api/workspace-views/")
        || path == "/api/reports"
        || path.starts_with("/api/reports/")
        || path.starts_with("/api/orgs/{org_id}/")
    {
        return service_plane.includes_control();
    }
    service_plane.includes_data()
}

#[utoipa::path(
    get,
    path = "/api/auth/config",
    tag = "auth",
    security(),
    responses(
        (status = 200, description = "Frontend auth provider availability", body = crate::http::openapi::AuthConfigResponse),
    ),
)]
pub async fn auth_config(State(state): State<Arc<AppState>>) -> Json<AuthConfigResponse> {
    let exposes_auth_routes = state.config.service_plane.includes_control();
    let clerk_jwt_issuer = if exposes_auth_routes && state.config.managed_clerk_enabled {
        state.config.clerk_jwt_issuer.clone()
    } else {
        None
    };
    Json(AuthConfigResponse {
        dev_auth_enabled: exposes_auth_routes && state.config.dev_auth_enabled,
        managed_clerk_enabled: exposes_auth_routes && state.config.managed_clerk_enabled,
        service_plane: state.config.service_plane.as_str().to_string(),
        clerk_jwt_issuer,
    })
}

pub async fn not_found() -> AppError {
    AppError::not_found("route not found")
}
